version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.2.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install --unsafe
      - run:
          name: build react
          command: npm run build
      - run:
          name: deploy firebase
          command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
