version: 2
jobs:
  deploy_dev:
    steps:
      - checkout
      - run:
        name: build
        command: npm run build
      - run:
        name: deploy to Firebase
        command: firebase deploy
workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
        filters:
          branches:
            only: master
